"""Simple Prover9 -> TPTP input translation helpers.
"""

import re
import json
import os
from pathlib import Path
from typing import Optional
import subprocess

project_root = Path(__file__).resolve().parents[2]
script_dir = os.path.dirname(os.path.abspath(__file__))


from dotenv import load_dotenv
import os

load_dotenv()
ladr_root = os.getenv("LADR_DIR")


def translate_prover9_to_tptp(text: str, problem_name: Optional[str] = None) -> str:
    binary = Path(ladr_root) / 'bin/ladr_to_tptp'
	#run 'ladr_to_tptp -q on the input text'
    command = f"{binary.as_posix()} -q"
    result = subprocess.run(['/bin/zsh', '-lc', command], input=text, capture_output=True, text=True, timeout=30)
    tptp_text = result.stdout
    return tptp_text

def rename_constants(tptp_text: str) -> str:
	# Renames the constants generated by ladr_to_tptp to more readable ones
    map_to_new_constants = {
		"'*'": "op",
		"'0'": "zero",
		"'\\''": "inv",
		"'\\'": "ldiv",
		"'/'": "rdiv",
    }
	
    # replace all occurrences of the keys in map_to_new_constants with their corresponding values
    for old, new in map_to_new_constants.items():
        tptp_text = re.sub(re.escape(old), new, tptp_text)
    return tptp_text

def convert_prover9_dir_to_tptp(overwrite=True):
	"""
		Convert every file in `prover9` to TPTP and write into `tptp_dir`.
	"""
	prover9_dir = Path(script_dir) / 'prover9'
	tptp_dir = Path(script_dir) / 'tptp'
	tptp_dir.mkdir(exist_ok=True)

	for p in sorted(prover9_dir.iterdir()):
		if not p.is_file():
			continue
		# Read content
		text = p.read_text()
		tptp_text = translate_prover9_to_tptp(text, problem_name=p.stem)
		tptp_text = rename_constants(tptp_text)
		goals = []
		axioms = ""
		for line in tptp_text.splitlines():
			if line.startswith('fof(') and 'conjecture' in line:
				goals.append(line)
			else:
				axioms += line + "\n"
		for i, goal in enumerate(goals):
			goal_name = f"{p.stem}_goal_{i+1}"
			goal_line = re.sub(r'fof\(([^,]+), conjecture,', f'fof({goal_name}, conjecture,', goal)
			final_text = axioms + goal_line + "\n"
			out_path = tptp_dir / f"{goal_name}.p"
			if out_path.exists() and not overwrite:
				print(f"Skipping existing file {out_path}")
				continue
			out_path.write_text(final_text)


if __name__ == '__main__':
	written = convert_prover9_dir_to_tptp()


