% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 4118
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT m(X, Y) = m(m(m(X, X), X), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(m(a, a), a), b) ).
