% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 2449
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(m(X, m(m(X, Y), Y)), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(a, b), b)), a) ).
