% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 4146
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT m(X, Y) = m(m(m(X, Z), Z), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(m(a, c), c), b) ).
