% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 4585
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT m(m(X, X), X) = m(m(X, Y), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, a), a) != m(m(a, b), b) ).
