% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 962
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(Y, m(m(Z, Y), m(X, Z)))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(c, b), m(a, c))) ).
