% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 437
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(X, m(Y, m(Y, m(X, Y))))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(b, m(b, m(a, b)))) ).
