% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 1873
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(m(X, m(Y, Z)), m(Y, Z))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(b, c)), m(b, c)) ).
