% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 1110
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(Y, m(m(Y, m(X, X)), Y))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(b, m(a, a)), b)) ).
