% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 1278
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(Y, m(m(m(X, X), Y), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(m(a, a), b), a)) ).
