% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 3083
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(m(m(m(X, Y), Y), Z), Z)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(m(a, b), b), c), c) ).
