% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 3459
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT m(X, X) = m(X, m(m(X, Y), Y))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(a, m(m(a, b), b)) ).
