% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 3924
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT m(X, Y) = m(m(X, m(Y, X)), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(a, m(b, a)), a) ).
