% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 949
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT X = m(Y, m(m(Z, X), m(Y, Z)))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(c, a), m(b, c))) ).
