% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1076 AND NOT 4068
% X = m(Y, m(m(X, m(X, Y)), Y)) AND NOT m(X, X) = m(m(m(X, X), Y), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, m(X, Y)), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(m(a, a), b), b) ).
