% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1117 AND NOT 2530
% X = m(Y, m(m(Y, m(X, Z)), Z)) AND NOT X = m(m(Y, m(m(Y, X), X)), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(X, Z)), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(m(b, a), a)), a) ).
