% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1133 AND NOT 4689
% X = m(Y, m(m(Y, m(Z, Y)), X)) AND NOT m(m(X, Y), Z) = m(m(W, Y), Z)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(Z, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, b), c) != m(m(d, b), c) ).
