% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1133 AND NOT 1721
% X = m(Y, m(m(Y, m(Z, Y)), X)) AND NOT X = m(m(Y, Y), m(m(X, Y), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(Z, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, b), m(m(a, b), a)) ).
