% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1133 AND NOT 3989
% X = m(Y, m(m(Y, m(Z, Y)), X)) AND NOT m(X, Y) = m(m(Z, m(X, X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(Z, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(c, m(a, a)), b) ).
