% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1133 AND NOT 2000
% X = m(Y, m(m(Y, m(Z, Y)), X)) AND NOT X = m(m(Y, m(Z, Z)), m(Z, X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(Z, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(c, c)), m(c, a)) ).
