% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1133 AND NOT 4615
% X = m(Y, m(m(Y, m(Z, Y)), X)) AND NOT m(m(X, X), Y) = m(m(Z, X), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(Z, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, a), b) != m(m(c, a), b) ).
