% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1133 AND NOT 1701
% X = m(Y, m(m(Y, m(Z, Y)), X)) AND NOT X = m(m(Y, X), m(m(Z, X), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, m(Z, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, a), m(m(c, a), a)) ).
