% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 1025
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT X = m(X, m(m(X, m(Y, X)), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(a, m(b, a)), a)) ).
