% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 2024
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT X = m(m(Y, m(Z, W)), m(W, X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(c, d)), m(d, a)) ).
