% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 1096
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT X = m(Y, m(m(X, m(Z, Y)), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(a, m(c, b)), a)) ).
