% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 3925
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT m(X, Y) = m(m(X, m(Y, X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(a, m(b, a)), b) ).
