% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 1763
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT X = m(m(Y, Z), m(m(X, Z), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, c), m(m(a, c), a)) ).
