% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 4040
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT m(X, Y) = m(m(Z, m(W, X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(c, m(d, a)), b) ).
