% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1167 AND NOT 1847
% X = m(Y, m(m(Z, m(Y, Y)), X)) AND NOT X = m(m(X, m(Y, X)), m(X, X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Z, m(Y, Y)), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(b, a)), m(a, a)) ).
