% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1286 AND NOT 614
% X = m(Y, m(m(m(X, Y), X), Y)) AND NOT X = m(X, m(X, m(m(X, X), X)))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(m(X, Y), X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(a, m(m(a, a), a))) ).
