% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1286 AND NOT 2504
% X = m(Y, m(m(m(X, Y), X), Y)) AND NOT X = m(m(Y, m(m(X, Y), X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(m(X, Y), X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(m(a, b), a)), b) ).
