% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1286 AND NOT 3915
% X = m(Y, m(m(m(X, Y), X), Y)) AND NOT m(X, Y) = m(m(X, m(X, X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(m(X, Y), X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(a, m(a, a)), b) ).
