% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1289 AND NOT 3116
% X = m(Y, m(m(m(X, Y), Y), Y)) AND NOT X = m(m(m(m(Y, X), Y), Y), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(m(X, Y), Y), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(m(b, a), b), b), b) ).
