% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1323 AND NOT 2744
% X = m(Y, m(m(m(Y, Y), X), Y)) AND NOT X = m(m(m(Y, Y), m(Y, X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(m(Y, Y), X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, b), m(b, a)), b) ).
