% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1437 AND NOT 4316
% X = m(m(X, X), m(Y, m(Z, X))) AND NOT m(X, m(Y, X)) = m(X, m(Z, X))
% LHS
cnf(left, axiom,
    X = m(m(X, X), m(Y, m(Z, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, a)) != m(a, m(c, a)) ).
