% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1447 AND NOT 1431
% X = m(m(X, Y), m(X, m(Z, X))) AND NOT X = m(m(X, X), m(Y, m(X, X)))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(X, m(Z, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, a), m(b, m(a, a))) ).
