% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1447 AND NOT 4269
% X = m(m(X, Y), m(X, m(Z, X))) AND NOT m(X, m(X, X)) = m(X, m(Y, X))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(X, m(Z, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(a, a)) != m(a, m(b, a)) ).
