% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1485 AND NOT 3955
% X = m(m(Y, X), m(X, m(Z, Y))) AND NOT m(X, Y) = m(m(Y, m(X, Y)), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(X, m(Z, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(b, m(a, b)), b) ).
