% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1485 AND NOT 1481
% X = m(m(Y, X), m(X, m(Z, Y))) AND NOT X = m(m(Y, X), m(X, m(Y, X)))
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(X, m(Z, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, a), m(a, m(b, a))) ).
