% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1485 AND NOT 2163
% X = m(m(Y, X), m(X, m(Z, Y))) AND NOT X = m(m(m(Y, Z), X), m(X, Z))
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(X, m(Z, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, c), a), m(a, c)) ).
