% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1491 AND NOT 65
% X = m(m(Y, X), m(Y, m(Y, X))) AND NOT X = m(Y, m(X, m(Y, X)))
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(Y, m(Y, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(a, m(b, a))) ).
