% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1516 AND NOT 1489
% X = m(m(Y, Y), m(X, m(X, Y))) AND NOT X = m(m(Y, X), m(Y, m(X, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(X, m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, a), m(b, m(a, b))) ).
