% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1526 AND NOT 1223
% X = m(m(Y, Y), m(Y, m(X, Y))) AND NOT X = m(X, m(m(m(X, X), X), X))
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(Y, m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(m(a, a), a), a)) ).
