% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1526 AND NOT 2744
% X = m(m(Y, Y), m(Y, m(X, Y))) AND NOT X = m(m(m(Y, Y), m(Y, X)), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(Y, m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, b), m(b, a)), b) ).
