% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1526 AND NOT 1323
% X = m(m(Y, Y), m(Y, m(X, Y))) AND NOT X = m(Y, m(m(m(Y, Y), X), Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(Y, m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(m(b, b), a), b)) ).
