% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1648 AND NOT 151
% X = m(m(X, Y), m(m(X, Y), Y)) AND NOT X = m(m(X, X), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(X, Y), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, a), m(a, a)) ).
