% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1648 AND NOT 2238
% X = m(m(X, Y), m(m(X, Y), Y)) AND NOT X = m(m(X, m(X, m(X, X))), X)
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(X, Y), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(a, m(a, a))), a) ).
