% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 4339
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT m(X, m(Y, Y)) = m(X, m(Y, Z))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, b)) != m(a, m(b, c)) ).
