% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 1872
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT X = m(m(X, m(Y, Z)), m(Y, Y))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(b, c)), m(b, b)) ).
