% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 1661
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT X = m(m(X, Y), m(m(Y, Z), Y))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, b), m(m(b, c), b)) ).
