% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 4357
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT m(X, m(Y, Z)) = m(X, m(Y, W))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, c)) != m(a, m(b, d)) ).
