% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 3524
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT m(X, Y) = m(X, m(m(Y, Z), X))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(b, c), a)) ).
