% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 1633
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT X = m(m(X, X), m(m(X, Y), Z))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, a), m(m(a, b), c)) ).
