% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1659 AND NOT 1860
% X = m(m(X, Y), m(m(Y, Y), Z)) AND NOT X = m(m(X, m(Y, Y)), m(Y, X))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Y), Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(b, b)), m(b, a)) ).
