% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1661 AND NOT 1837
% X = m(m(X, Y), m(m(Y, Z), Y)) AND NOT X = m(m(X, m(X, Y)), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Z), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(a, b)), m(a, a)) ).
