% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1661 AND NOT 3520
% X = m(m(X, Y), m(m(Y, Z), Y)) AND NOT m(X, Y) = m(X, m(m(Y, X), Z))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Z), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(b, a), c)) ).
