% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1661 AND NOT 2443
% X = m(m(X, Y), m(m(Y, Z), Y)) AND NOT X = m(m(X, m(m(X, X), Y)), X)
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Z), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(a, a), b)), a) ).
