% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1661 AND NOT 1657
% X = m(m(X, Y), m(m(Y, Z), Y)) AND NOT X = m(m(X, Y), m(m(Y, Y), X))
% LHS
cnf(left, axiom,
    X = m(m(X, Y), m(m(Y, Z), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, b), m(m(b, b), a)) ).
