% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1692 AND NOT 2441
% X = m(m(Y, X), m(m(Y, X), Y)) AND NOT X = m(m(X, m(m(X, X), X)), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(m(Y, X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(a, a), a)), a) ).
