% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1692 AND NOT 63
% X = m(m(Y, X), m(m(Y, X), Y)) AND NOT X = m(Y, m(X, m(X, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(m(Y, X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(a, m(a, b))) ).
