% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1692 AND NOT 1922
% X = m(m(Y, X), m(m(Y, X), Y)) AND NOT X = m(m(Y, m(Y, X)), m(X, Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(m(Y, X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(b, a)), m(a, b)) ).
