% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1701 AND NOT 3862
% X = m(m(Y, X), m(m(Z, X), X)) AND NOT m(X, X) = m(m(X, m(X, X)), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, X), m(m(Z, X), X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(a, m(a, a)), a) ).
