% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1722 AND NOT 1832
% X = m(m(Y, Y), m(m(X, Y), Y)) AND NOT X = m(m(X, m(X, X)), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(m(X, Y), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(a, a)), m(a, a)) ).
