% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1722 AND NOT 3050
% X = m(m(Y, Y), m(m(X, Y), Y)) AND NOT X = m(m(m(m(X, X), X), X), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(m(X, Y), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(m(a, a), a), a), a) ).
