% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1729 AND NOT 917
% X = m(m(Y, Y), m(m(Y, X), Y)) AND NOT X = m(Y, m(m(Y, Y), m(X, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, Y), m(m(Y, X), Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(b, b), m(a, b))) ).
