% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1839 AND NOT 4065
% X = m(m(X, m(X, Y)), m(X, Z)) AND NOT m(X, X) = m(m(m(X, X), X), X)
% LHS
cnf(left, axiom,
    X = m(m(X, m(X, Y)), m(X, Z)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(m(a, a), a), a) ).
