% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1895 AND NOT 271
% X = m(m(Y, m(X, Y)), m(X, Y)) AND NOT X = m(m(m(Y, X), X), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, Y)), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, a), a), b) ).
