% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1895 AND NOT 8
% X = m(m(Y, m(X, Y)), m(X, Y)) AND NOT X = m(X, m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, Y)), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(a, a)) ).
