% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1898 AND NOT 2710
% X = m(m(Y, m(X, Y)), m(Y, Y)) AND NOT X = m(m(m(Y, X), m(Y, Y)), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, Y)), m(Y, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, a), m(b, b)), b) ).
