% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1924 AND NOT 3253
% X = m(m(Y, m(Y, X)), m(Y, X)) AND NOT m(X, X) = m(X, m(X, m(X, X)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Y, X)), m(Y, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(a, m(a, m(a, a))) ).
