% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1924 AND NOT 3915
% X = m(m(Y, m(Y, X)), m(Y, X)) AND NOT m(X, Y) = m(m(X, m(X, X)), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Y, X)), m(Y, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(a, m(a, a)), b) ).
