% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1925 AND NOT 910
% X = m(m(Y, m(Y, X)), m(Y, Y)) AND NOT X = m(Y, m(m(Y, X), m(Y, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Y, X)), m(Y, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(b, a), m(b, b))) ).
