% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1979 AND NOT 1884
% X = m(m(Y, m(Z, Y)), m(Y, X)) AND NOT X = m(m(Y, m(X, X)), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Y)), m(Y, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(a, a)), m(a, a)) ).
