% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1979 AND NOT 1742
% X = m(m(Y, m(Z, Y)), m(Y, X)) AND NOT X = m(m(Y, Y), m(m(Z, Y), X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Y)), m(Y, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, b), m(m(c, b), a)) ).
