% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1979 AND NOT 4645
% X = m(m(Y, m(Z, Y)), m(Y, X)) AND NOT m(m(X, Y), X) = m(m(Z, Y), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Y)), m(Y, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, b), a) != m(m(c, b), a) ).
