% generated by generate_tptp_for_unknown.py on 2025-08-02
% 1979 AND NOT 3952
% X = m(m(Y, m(Z, Y)), m(Y, X)) AND NOT m(X, Y) = m(m(Y, m(X, X)), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Y)), m(Y, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(b, m(a, a)), b) ).
