% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2000 AND NOT 4666
% X = m(m(Y, m(Z, Z)), m(Z, X)) AND NOT m(m(X, Y), Y) = m(m(Z, Y), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Z)), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, b), b) != m(m(c, b), b) ).
