% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2000 AND NOT 1797
% X = m(m(Y, m(Z, Z)), m(Z, X)) AND NOT X = m(m(Y, Z), m(m(Z, Z), X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Z)), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, c), m(m(c, c), a)) ).
