% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2000 AND NOT 3935
% X = m(m(Y, m(Z, Z)), m(Z, X)) AND NOT m(X, Y) = m(m(X, m(Z, X)), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Z)), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(a, m(c, a)), b) ).
