% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2000 AND NOT 1668
% X = m(m(Y, m(Z, Z)), m(Z, X)) AND NOT X = m(m(X, Y), m(m(Z, Y), X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Z)), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, b), m(m(c, b), a)) ).
