% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2000 AND NOT 1055
% X = m(m(Y, m(Z, Z)), m(Z, X)) AND NOT X = m(X, m(m(Y, m(Z, X)), X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Z)), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(b, m(c, a)), a)) ).
