% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2000 AND NOT 2024
% X = m(m(Y, m(Z, Z)), m(Z, X)) AND NOT X = m(m(Y, m(Z, W)), m(W, X))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Z, Z)), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(c, d)), m(d, a)) ).
