% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2054 AND NOT 255
% X = m(m(m(X, Y), X), m(Y, Y)) AND NOT X = m(m(m(X, X), X), X)
% LHS
cnf(left, axiom,
    X = m(m(m(X, Y), X), m(Y, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(a, a), a), a) ).
