% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2056 AND NOT 4584
% X = m(m(m(X, Y), X), m(Z, X)) AND NOT m(m(X, X), X) = m(m(X, Y), X)
% LHS
cnf(left, axiom,
    X = m(m(m(X, Y), X), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, a), a) != m(m(a, b), a) ).
