% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2056 AND NOT 2040
% X = m(m(m(X, Y), X), m(Z, X)) AND NOT X = m(m(m(X, X), Y), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(m(X, Y), X), m(Z, X)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(a, a), b), m(a, a)) ).
