% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2091 AND NOT 2098
% X = m(m(m(Y, X), X), m(Y, Y)) AND NOT X = m(m(m(Y, X), Y), m(X, Y))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), X), m(Y, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, a), b), m(a, b)) ).
