% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2101 AND NOT 2304
% X = m(m(m(Y, X), Y), m(Y, Y)) AND NOT X = m(m(Y, m(X, m(Y, Y))), Y)
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), Y), m(Y, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(a, m(b, b))), b) ).
