% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2162 AND NOT 2087
% X = m(m(m(Y, Z), X), m(X, Y)) AND NOT X = m(m(m(Y, X), X), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, Z), X), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, a), a), m(a, a)) ).
