% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2162 AND NOT 1427
% X = m(m(m(Y, Z), X), m(X, Y)) AND NOT X = m(m(X, X), m(X, m(X, Y)))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, Z), X), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, a), m(a, m(a, b))) ).
