% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2162 AND NOT 3877
% X = m(m(m(Y, Z), X), m(X, Y)) AND NOT m(X, X) = m(m(Y, m(X, X)), X)
% LHS
cnf(left, axiom,
    X = m(m(m(Y, Z), X), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(b, m(a, a)), a) ).
