% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2162 AND NOT 3955
% X = m(m(m(Y, Z), X), m(X, Y)) AND NOT m(X, Y) = m(m(Y, m(X, Y)), Y)
% LHS
cnf(left, axiom,
    X = m(m(m(Y, Z), X), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(b, m(a, b)), b) ).
