% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2162 AND NOT 3511
% X = m(m(m(Y, Z), X), m(X, Y)) AND NOT m(X, Y) = m(X, m(m(X, Y), X))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, Z), X), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(a, b), a)) ).
