% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2162 AND NOT 3457
% X = m(m(m(Y, Z), X), m(X, Y)) AND NOT m(X, X) = m(X, m(m(X, X), Y))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, Z), X), m(X, Y)) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(a, m(m(a, a), b)) ).
