% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2301 AND NOT 2847
% X = m(m(Y, m(X, m(Y, X))), Y) AND NOT X = m(m(m(X, m(X, X)), X), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, m(Y, X))), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(a, m(a, a)), a), a) ).
