% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2301 AND NOT 4470
% X = m(m(Y, m(X, m(Y, X))), Y) AND NOT m(X, m(Y, Y)) = m(m(X, X), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, m(Y, X))), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, b)) != m(m(a, a), b) ).
