% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2301 AND NOT 3319
% X = m(m(Y, m(X, m(Y, X))), Y) AND NOT m(X, Y) = m(X, m(Y, m(Y, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, m(Y, X))), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(b, m(b, b))) ).
