% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2301 AND NOT 1083
% X = m(m(Y, m(X, m(Y, X))), Y) AND NOT X = m(Y, m(m(X, m(Y, X)), Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, m(Y, X))), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(a, m(b, a)), b)) ).
