% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2304 AND NOT 883
% X = m(m(Y, m(X, m(Y, Y))), Y) AND NOT X = m(Y, m(m(X, Y), m(Y, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(X, m(Y, Y))), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(a, b), m(b, b))) ).
