% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2338 AND NOT 511
% X = m(m(Y, m(Y, m(Y, X))), Y) AND NOT X = m(Y, m(Y, m(Y, m(X, Y))))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(Y, m(Y, X))), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(b, m(b, m(a, b)))) ).
