% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2460 AND NOT 3456
% X = m(m(X, m(m(Y, X), Y)), Y) AND NOT m(X, X) = m(X, m(m(X, X), X))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, X), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(a, m(m(a, a), a)) ).
