% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2460 AND NOT 4065
% X = m(m(X, m(m(Y, X), Y)), Y) AND NOT m(X, X) = m(m(m(X, X), X), X)
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, X), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(m(a, a), a), a) ).
