% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2473 AND NOT 1871
% X = m(m(X, m(m(Y, Y), Z)), Y) AND NOT X = m(m(X, m(Y, Z)), m(Y, X))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Y), Z)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(b, c)), m(b, a)) ).
