% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2473 AND NOT 4315
% X = m(m(X, m(m(Y, Y), Z)), Y) AND NOT m(X, m(Y, X)) = m(X, m(Y, Z))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Y), Z)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, a)) != m(a, m(b, c)) ).
