% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2473 AND NOT 3460
% X = m(m(X, m(m(Y, Y), Z)), Y) AND NOT m(X, X) = m(X, m(m(X, Y), Z))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Y), Z)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(a, m(m(a, b), c)) ).
