% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2473 AND NOT 2489
% X = m(m(X, m(m(Y, Y), Z)), Y) AND NOT X = m(m(X, m(m(Y, Z), W)), Y)
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Y), Z)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(b, c), d)), b) ).
