% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 1839
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT X = m(m(X, m(X, Y)), m(X, Z))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(a, b)), m(a, c)) ).
