% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 2467
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT X = m(m(X, m(m(Y, Y), X)), Y)
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(b, b), a)), b) ).
