% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 1860
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT X = m(m(X, m(Y, Y)), m(Y, X))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(b, b)), m(b, a)) ).
