% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 3523
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT m(X, Y) = m(X, m(m(Y, Y), Z))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(b, b), c)) ).
