% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 1630
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT X = m(m(X, X), m(m(X, X), Y))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, a), m(m(a, a), b)) ).
