% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 1656
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT X = m(m(X, Y), m(m(Y, X), Z))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, b), m(m(b, a), c)) ).
