% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 4314
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT m(X, m(Y, X)) = m(X, m(Y, Y))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, a)) != m(a, m(b, b)) ).
