% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2481 AND NOT 4268
% X = m(m(X, m(m(Y, Z), Y)), Y) AND NOT m(X, m(X, X)) = m(X, m(X, Y))
% LHS
cnf(left, axiom,
    X = m(m(X, m(m(Y, Z), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(a, a)) != m(a, m(a, b)) ).
