% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 4479
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT m(X, m(Y, Y)) = m(m(Y, X), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(b, b)) != m(m(b, a), a) ).
