% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 4684
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT m(m(X, Y), Z) = m(m(Z, Y), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, b), c) != m(m(c, b), a) ).
