% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 474
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(Y, m(X, m(Y, m(X, Y))))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(a, m(b, m(a, b)))) ).
