% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 4636
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT m(m(X, Y), X) = m(m(Y, X), Y)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(m(a, b), a) != m(m(b, a), b) ).
