% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 3334
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT m(X, Y) = m(X, m(Z, m(Z, Y)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(c, m(c, b))) ).
