% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 817
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(X, m(m(X, X), m(X, X)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(a, a), m(a, a))) ).
