% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 1242
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(X, m(m(m(Y, X), Y), Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(m(b, a), b), b)) ).
