% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 3475
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT m(X, X) = m(Y, m(m(X, Y), Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(b, m(m(a, b), b)) ).
