% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 203
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(m(X, m(X, X)), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(a, a)), a) ).
