% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 2865
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(m(m(X, m(Y, X)), Y), X)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(a, m(b, a)), b), a) ).
