% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 1444
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(m(X, Y), m(X, m(Y, X)))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, b), m(a, m(b, a))) ).
