% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2531 AND NOT 2776
% X = m(m(Y, m(m(Y, X), X)), Y) AND NOT X = m(m(m(Y, Z), m(X, Y)), Z)
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), X)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, c), m(a, b)), c) ).
