% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2534 AND NOT 1113
% X = m(m(Y, m(m(Y, X), Y)), Y) AND NOT X = m(Y, m(m(Y, m(X, Y)), Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(b, m(a, b)), b)) ).
