% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2538 AND NOT 1113
% X = m(m(Y, m(m(Y, X), Z)), Z) AND NOT X = m(Y, m(m(Y, m(X, Y)), Y))
% LHS
cnf(left, axiom,
    X = m(m(Y, m(m(Y, X), Z)), Z) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(b, m(a, b)), b)) ).
