% generated by generate_tptp_for_unknown.py on 2025-08-02
% 261 AND NOT 2061
% X = m(m(m(X, Y), X), Y) AND NOT X = m(m(m(X, Y), Y), m(X, Y))
% LHS
cnf(left, axiom,
    X = m(m(m(X, Y), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(a, b), b), m(a, b)) ).
