% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2710 AND NOT 1832
% X = m(m(m(Y, X), m(Y, Y)), Y) AND NOT X = m(m(X, m(X, X)), m(X, X))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), m(Y, Y)), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(a, a)), m(a, a)) ).
