% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2712 AND NOT 2449
% X = m(m(m(Y, X), m(Y, Z)), X) AND NOT X = m(m(X, m(m(X, Y), Y)), X)
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), m(Y, Z)), X) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(a, b), b)), a) ).
