% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2712 AND NOT 3065
% X = m(m(m(Y, X), m(Y, Z)), X) AND NOT X = m(m(m(m(X, Y), X), X), X)
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), m(Y, Z)), X) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(m(a, b), a), a), a) ).
