% generated by generate_tptp_for_unknown.py on 2025-08-02
% 2712 AND NOT 3519
% X = m(m(m(Y, X), m(Y, Z)), X) AND NOT m(X, Y) = m(X, m(m(Y, X), Y))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), m(Y, Z)), X) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(b, a), b)) ).
