% generated by generate_tptp_for_unknown.py on 2025-08-02
% 271 AND NOT 1895
% X = m(m(m(Y, X), X), Y) AND NOT X = m(m(Y, m(X, Y)), m(X, Y))
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(a, b)), m(a, b)) ).
