% generated by generate_tptp_for_unknown.py on 2025-08-02
% 274 AND NOT 222
% X = m(m(m(Y, X), Y), Y) AND NOT X = m(m(Y, m(X, Y)), Y)
% LHS
cnf(left, axiom,
    X = m(m(m(Y, X), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(a, b)), b) ).
