% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3076 AND NOT 3253
% X = m(m(m(m(X, Y), Y), X), Y) AND NOT m(X, X) = m(X, m(X, m(X, X)))
% LHS
cnf(left, axiom,
    X = m(m(m(m(X, Y), Y), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(a, m(a, m(a, a))) ).
