% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3103 AND NOT 466
% X = m(m(m(m(Y, X), X), X), Y) AND NOT X = m(Y, m(X, m(X, m(Y, X))))
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), X), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(a, m(a, m(b, a)))) ).
