% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3103 AND NOT 1075
% X = m(m(m(m(Y, X), X), X), Y) AND NOT X = m(Y, m(m(X, m(X, Y)), X))
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), X), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(m(a, m(a, b)), a)) ).
