% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3113 AND NOT 3058
% X = m(m(m(m(Y, X), Y), X), Y) AND NOT X = m(m(m(m(X, X), Y), Y), X)
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), Y), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(m(a, a), b), b), a) ).
