% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3113 AND NOT 4068
% X = m(m(m(m(Y, X), Y), X), Y) AND NOT m(X, X) = m(m(m(X, X), Y), Y)
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), Y), X), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(m(a, a), b), b) ).
