% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3116 AND NOT 513
% X = m(m(m(m(Y, X), Y), Y), Y) AND NOT X = m(Y, m(Y, m(Y, m(Y, X))))
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), Y), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(b, m(b, m(b, a)))) ).
