% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3116 AND NOT 411
% X = m(m(m(m(Y, X), Y), Y), Y) AND NOT X = m(X, m(X, m(X, m(X, X))))
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), Y), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(a, m(a, m(a, a)))) ).
