% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3116 AND NOT 4380
% X = m(m(m(m(Y, X), Y), Y), Y) AND NOT m(X, m(X, X)) = m(m(X, X), X)
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), Y), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, m(a, a)) != m(m(a, a), a) ).
