% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3116 AND NOT 2913
% X = m(m(m(m(Y, X), Y), Y), Y) AND NOT X = m(m(m(Y, m(X, Y)), Y), Y)
% LHS
cnf(left, axiom,
    X = m(m(m(m(Y, X), Y), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(b, m(a, b)), b), b) ).
