% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3308 AND NOT 3511
% m(X, Y) = m(X, m(X, m(Y, X))) AND NOT m(X, Y) = m(X, m(m(X, Y), X))
% LHS
cnf(left, axiom,
    m(X, Y) = m(X, m(X, m(Y, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(a, b), a)) ).
