% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3342 AND NOT 3522
% m(X, Y) = m(Y, m(X, m(X, X))) AND NOT m(X, Y) = m(X, m(m(Y, Y), Y))
% LHS
cnf(left, axiom,
    m(X, Y) = m(Y, m(X, m(X, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(m(b, b), b)) ).
