% generated by generate_tptp_for_unknown.py on 2025-08-02
% 3342 AND NOT 4065
% m(X, Y) = m(Y, m(X, m(X, X))) AND NOT m(X, X) = m(m(m(X, X), X), X)
% LHS
cnf(left, axiom,
    m(X, Y) = m(Y, m(X, m(X, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(m(a, a), a), a) ).
