% generated by generate_tptp_for_unknown.py on 2025-08-02
% 4158 AND NOT 3955
% m(X, Y) = m(m(m(Y, X), Y), Y) AND NOT m(X, Y) = m(m(Y, m(X, Y)), Y)
% LHS
cnf(left, axiom,
    m(X, Y) = m(m(m(Y, X), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(m(b, m(a, b)), b) ).
