% generated by generate_tptp_for_unknown.py on 2025-08-02
% 4158 AND NOT 3862
% m(X, Y) = m(m(m(Y, X), Y), Y) AND NOT m(X, X) = m(m(X, m(X, X)), X)
% LHS
cnf(left, axiom,
    m(X, Y) = m(m(m(Y, X), Y), Y) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(a, m(a, a)), a) ).
