% generated by generate_tptp_for_unknown.py on 2025-08-02
% 4167 AND NOT 3319
% m(X, Y) = m(m(m(Y, Y), Y), X) AND NOT m(X, Y) = m(X, m(Y, m(Y, Y)))
% LHS
cnf(left, axiom,
    m(X, Y) = m(m(m(Y, Y), Y), X) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(b, m(b, b))) ).
