% generated by generate_tptp_for_unknown.py on 2025-08-02
% 464 AND NOT 2457
% X = m(Y, m(X, m(X, m(X, Y)))) AND NOT X = m(m(X, m(m(Y, X), X)), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(X, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(b, a), a)), b) ).
