% generated by generate_tptp_for_unknown.py on 2025-08-02
% 474 AND NOT 436
% X = m(Y, m(X, m(Y, m(X, Y)))) AND NOT X = m(X, m(Y, m(Y, m(X, X))))
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(Y, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(b, m(b, m(a, a)))) ).
