% generated by generate_tptp_for_unknown.py on 2025-08-02
% 474 AND NOT 3278
% X = m(Y, m(X, m(Y, m(X, Y)))) AND NOT m(X, X) = m(Y, m(Y, m(X, X)))
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(Y, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(b, m(b, m(a, a))) ).
