% generated by generate_tptp_for_unknown.py on 2025-08-02
% 476 AND NOT 4065
% X = m(Y, m(X, m(Y, m(Y, X)))) AND NOT m(X, X) = m(m(m(X, X), X), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(Y, m(Y, X)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(m(a, a), a), a) ).
