% generated by generate_tptp_for_unknown.py on 2025-08-02
% 511 AND NOT 714
% X = m(Y, m(Y, m(Y, m(X, Y)))) AND NOT X = m(Y, m(Y, m(m(Y, X), Y)))
% LHS
cnf(left, axiom,
    X = m(Y, m(Y, m(Y, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(b, m(b, m(m(b, a), b))) ).
