% generated by generate_tptp_for_unknown.py on 2025-08-02
% 511 AND NOT 2338
% X = m(Y, m(Y, m(Y, m(X, Y)))) AND NOT X = m(m(Y, m(Y, m(Y, X))), Y)
% LHS
cnf(left, axiom,
    X = m(Y, m(Y, m(Y, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, m(b, m(b, a))), b) ).
