% generated by generate_tptp_for_unknown.py on 2025-08-02
% 511 AND NOT 2441
% X = m(Y, m(Y, m(Y, m(X, Y)))) AND NOT X = m(m(X, m(m(X, X), X)), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(Y, m(Y, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(a, m(m(a, a), a)), a) ).
