% generated by generate_tptp_for_unknown.py on 2025-08-02
% 511 AND NOT 1020
% X = m(Y, m(Y, m(Y, m(X, Y)))) AND NOT X = m(X, m(m(X, m(X, X)), X))
% LHS
cnf(left, axiom,
    X = m(Y, m(Y, m(Y, m(X, Y)))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(a, m(a, a)), a)) ).
