% generated by generate_tptp_for_unknown.py on 2025-08-02
% 63 AND NOT 1692
% X = m(Y, m(X, m(X, Y))) AND NOT X = m(m(Y, X), m(m(Y, X), Y))
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, a), m(m(b, a), b)) ).
