% generated by generate_tptp_for_unknown.py on 2025-08-02
% 65 AND NOT 1491
% X = m(Y, m(X, m(Y, X))) AND NOT X = m(m(Y, X), m(Y, m(Y, X)))
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(Y, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, a), m(b, m(b, a))) ).
