% generated by generate_tptp_for_unknown.py on 2025-08-02
% 65 AND NOT 359
% X = m(Y, m(X, m(Y, X))) AND NOT m(X, X) = m(m(X, X), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(X, m(Y, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(a, a), a) ).
