% generated by generate_tptp_for_unknown.py on 2025-08-02
% 854 AND NOT 3316
% X = m(X, m(m(Y, Z), m(X, Z))) AND NOT m(X, Y) = m(X, m(Y, m(X, Y)))
% LHS
cnf(left, axiom,
    X = m(X, m(m(Y, Z), m(X, Z))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, b) != m(a, m(b, m(a, b))) ).
