% generated by generate_tptp_for_unknown.py on 2025-08-02
% 854 AND NOT 413
% X = m(X, m(m(Y, Z), m(X, Z))) AND NOT X = m(X, m(X, m(X, m(Y, X))))
% LHS
cnf(left, axiom,
    X = m(X, m(m(Y, Z), m(X, Z))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(a, m(a, m(b, a)))) ).
