% generated by generate_tptp_for_unknown.py on 2025-08-02
% 883 AND NOT 2035
% X = m(Y, m(m(X, Y), m(Y, Y))) AND NOT X = m(m(m(X, X), X), m(X, X))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(X, Y), m(Y, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(m(a, a), a), m(a, a)) ).
