% generated by generate_tptp_for_unknown.py on 2025-08-02
% 906 AND NOT 3862
% X = m(Y, m(m(Y, X), m(X, X))) AND NOT m(X, X) = m(m(X, m(X, X)), X)
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, X), m(X, X))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    m(a, a) != m(m(a, m(a, a)), a) ).
