% generated by generate_tptp_for_unknown.py on 2025-08-02
% 907 AND NOT 836
% X = m(Y, m(m(Y, X), m(X, Y))) AND NOT X = m(X, m(m(Y, X), m(Y, Y)))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, X), m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(a, m(m(b, a), m(b, b))) ).
