% generated by generate_tptp_for_unknown.py on 2025-08-02
% 917 AND NOT 1729
% X = m(Y, m(m(Y, Y), m(X, Y))) AND NOT X = m(m(Y, Y), m(m(Y, X), Y))
% LHS
cnf(left, axiom,
    X = m(Y, m(m(Y, Y), m(X, Y))) ).

% RHS negated and skolemized
cnf(right, negated_conjecture,
    a != m(m(b, b), m(m(b, a), b)) ).
