twee:
  flags:
  - --all-lemmas
  - --show-peaks
  - --hint-skel-factor 0.2
  - --hint-skel-cost 0
  - --flatten-goal
  timeout: 1000
stitch:
  iterations: 10
  max_arity: 10
extraction:
  onlyProofTerms: true
  onlyPeakTerms: false
